BEMServer/bemserver-api

.github/workflows/tests.yaml

Related to https://github.com/timescale/docs/pull/234.

CI: Use PackageCloud to install Timescale

---

bemserver_api/extensions/smorest.py
bemserver_api/resources/campaigns/routes.py
bemserver_api/resources/campaigns/schemas.py
bemserver_api/resources/events/schemas.py
bemserver_api/resources/timeseries/routes.py
bemserver_api/resources/timeseries/schemas.py
bemserver_api/resources/timeseries_by_campaigns/schemas.py
bemserver_api/resources/timeseries_by_campaigns_by_users/schemas.py
bemserver_api/resources/timeseries_data/schemas.py
bemserver_api/resources/users/routes.py
bemserver_api/resources/users/schemas.py
bemserver_api/resources/users_by_campaigns/schemas.py
setup.py

Also don't use custom Schema when not needed (but vanilla marshmallow Schema)

Use SQLAlchemy objects update method to update items on PUT

---

bemserver_api/resources/timeseries_by_campaigns/schemas.py
bemserver_api/resources/timeseries_data/schemas.py
bemserver_api/resources/users_by_campaigns/schemas.py

- Use `include_fk` when relevant
- Remove unused `TimeseriesDataSchema`

Rework schemas

---

bemserver_api/resources/event_channels/schemas.py
requirements/install.txt
setup.py
tests/resources/test_event_channels.py

Core update: filter event channels by user

---

bemserver_api/extensions/smorest.py
bemserver_api/resources/campaign_scopes/schemas.py
bemserver_api/resources/campaigns/schemas.py
bemserver_api/resources/events/schemas.py
bemserver_api/resources/timeseries/schemas.py
bemserver_api/resources/timeseries_data/schemas.py
bemserver_api/resources/timeseries_property_data/schemas.py
bemserver_api/resources/user_groups/schemas.py
bemserver_api/resources/user_groups_by_campaign_scopes/schemas.py
bemserver_api/resources/user_groups_by_campaigns/schemas.py
bemserver_api/resources/users/schemas.py
bemserver_api/resources/users_by_user_groups/schemas.py

Makes schemas ordered in API docs

Use base Schema for all API schemas

---

bemserver_api/resources/buildings/schemas.py
bemserver_api/resources/campaign_scopes/schemas.py
bemserver_api/resources/campaigns/schemas.py
bemserver_api/resources/event_categories/schemas.py
bemserver_api/resources/event_levels/schemas.py
bemserver_api/resources/event_states/schemas.py
bemserver_api/resources/sites/schemas.py
bemserver_api/resources/spaces/schemas.py
bemserver_api/resources/storeys/schemas.py
bemserver_api/resources/timeseries/schemas.py
bemserver_api/resources/timeseries_properties/schemas.py
bemserver_api/resources/zones/schemas.py

Allow empty strings for non-required fields

---

bemserver_api/resources/building_properties/routes.py
bemserver_api/resources/buildings/routes.py
bemserver_api/resources/campaign_scopes/routes.py
bemserver_api/resources/campaigns/routes.py
bemserver_api/resources/site_properties/routes.py
bemserver_api/resources/sites/routes.py
bemserver_api/resources/space_properties/routes.py
bemserver_api/resources/spaces/routes.py
bemserver_api/resources/storey_properties/routes.py
bemserver_api/resources/storeys/routes.py
bemserver_api/resources/structural_element_properties/routes.py
bemserver_api/resources/timeseries/routes.py
bemserver_api/resources/timeseries_data_states/routes.py
bemserver_api/resources/timeseries_properties/routes.py
bemserver_api/resources/user_groups/routes.py
bemserver_api/resources/users/routes.py
bemserver_api/resources/zone_properties/routes.py
bemserver_api/resources/zones/routes.py

Those are useless and add wrong information to the docs.

Remove unneeded uses of catch_integrity_error

---

bemserver_api/extensions/smorest.py
bemserver_api/resources/building_properties/schemas.py
bemserver_api/resources/site_properties/schemas.py
bemserver_api/resources/space_properties/schemas.py
bemserver_api/resources/storey_properties/schemas.py
bemserver_api/resources/zone_properties/schemas.py
requirements/install.txt
setup.py
tests/resources/test_building_properties.py
tests/resources/test_site_properties.py
tests/resources/test_space_properties.py
tests/resources/test_storey_properties.py
tests/resources/test_zone_properties.py

The custom schema resolver avoid a warning from apispec complaining that several schemas resolve to the same name.

Dump structural element property with site, building,... properties

---

bemserver_api/resources/input_output/routes.py
bemserver_api/resources/timeseries_data/routes.py
requirements/install.txt
setup.py
tests/resources/test_timeseries_data.py

TimeseriesDataIO improvements

---

requirements/install.txt
setup.py
tests/resources/test_timeseries_data.py

Core update: Fix TimeseriesDataIO.delete: do commit

---

bemserver_api/resources/analysis/__init__.py
bemserver_api/resources/analysis/routes.py
bemserver_api/resources/analysis/schemas.py
tests/resources/test_analysis.py

Also, don't require campaign for completeness. Work with TS IDs.

Move AnalysisForCampaign to Analysis

---

bemserver_api/resources/timeseries_data/routes.py
requirements/install.txt
setup.py
tests/resources/test_timeseries_data.py

Core update: TimeseriesDataCSVIO.export_csv: add "timezone" parameter

---

bemserver_api/__init__.py
bemserver_api/extensions/authentication.py

app is not needed, this can be done on import

Remove authentication.init_app

---

bemserver_api/resources/campaigns/schemas.py
bemserver_api/resources/energy_consumption_timeseries_by_buildings/schemas.py
bemserver_api/resources/energy_consumption_timeseries_by_sites/schemas.py
bemserver_api/resources/st_cleanups_by_campaigns/schemas.py
bemserver_api/resources/structural_element_properties/schemas.py
bemserver_api/resources/timeseries_properties/schemas.py
tests/resources/test_structural_element_properties.py
tests/resources/test_timeseries_properties.py

Also modify tests to avoid using enum from bemserver_core.

Document default values in API docs

---

bemserver_api/resources/analysis/completeness/schemas.py
bemserver_api/resources/analysis/energy_consumption/schemas.py
bemserver_api/resources/timeseries_data/schemas.py
requirements/install.txt
setup.py
tests/resources/test_timeseries_data.py

- Upgrade bemserver-core
- Update imports for (PERIODS, FIXED_SIZE_PERIODS) and use time_utils
- Create TimeseriesBucketWidthSchema that can validate bucket width unit and value consistency
- Use this schema in TimeseriesData with aggregation, Completeness and Energy consumption resources

Bump bemserver-core version (following ts buckets rework)

---

bemserver_api/resources/timeseries_data/routes.py
bemserver_api/resources/timeseries_data/schemas.py
requirements/install.txt
setup.py
tests/resources/test_timeseries_data.py

Timeseries data IO 
- JSON I/O
- data in request/response body rather than attached file

Core update: TimeseriesData IO rework, JSON I/O

---

bemserver_api/resources/energy_consumption_timeseries_by_buildings/schemas.py
bemserver_api/resources/energy_consumption_timeseries_by_sites/schemas.py
bemserver_api/resources/energy_production_timeseries_by_buildings/schemas.py
bemserver_api/resources/energy_production_timeseries_by_sites/schemas.py

Fix Energy Consumption/Production TS x Site/Building schemas

---

bemserver_api/resources/input_output/routes.py
bemserver_api/resources/notifications/routes.py
bemserver_api/resources/timeseries_data/routes.py
requirements/install.txt
setup.py

Core update: Rework session management

---

bemserver_api/resources/sites/routes.py
bemserver_api/resources/sites/schemas.py
requirements/install.txt
setup.py
tests/resources/test_sites.py

Requires bemserver_core 0.13.2

Add Site degree_days resource

---

src/bemserver_api/__init__.py

Sorting keys is not so useful. Removing it might speed up things a bit.
See https://stackoverflow.com/a/54446470/4653485.

Set app.json.sort_keys = False
